### ISSUE TITLE
remove-sidenav conflicting with horizontal layout

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/website-v2-docs#322]
When we remove the sidenav in the antora configuration:

```yaml
asciidoc:
  attributes:
    # Enable pagination
    page-pagination: ''
    # Remove the sidenav and include TOC in index.adoc page
    remove-sidenav: ''
```

which is what [the playbook for libraries](https://github.com/boostorg/website-v2-docs/blob/develop/libs.playbook.yml) does, the layout does not use the horizontal space.

Here's the output with sitedocs:

![image](https://github.com/user-attachments/assets/0044c3c3-9b46-44fa-8b11-1084d6794851)

And here's the output for libraries:

![image](https://github.com/user-attachments/assets/4f5e6d7d-f478-4824-a73c-b14edb290a60)

This is a serious issue as we intend to enable the Antora documentation in the boost release tools soon.
